@startuml
!include HypothesisMap.puml

Goal(G1, "Тестовая цель")

Metric(M1, G1, "Метрика 1", 1)
Group(Group1, "Группа 1") {
    Metric(M2, G1, "Метрика 2", 1)
    Metric(M3, G1, "Метрика 3", 1)
}

Subject(S1, "M1;M2;M3", "Описание субъекта 1", "Боли субъекта 1", "Желания субъекта 1", 1)

Decision(D1, S1)

Hypothesis(H1, "D1:Условие 1", "Если", "То", "Потому что", 1, 1, "новая")
Hypothesis(H2, "D1:Условие 2", "Если", "То", "Потому что", 1, 1, "новая")

Task(T1, H1, "Описание задачи 1", 23, "2025-06-20")

SHOW_LEGEND()
@enduml